version: "3"
services:
  gatekeeper:
    build: ./gatekeeper
    command: python -u gatekeeper.py
    ports:
      - "80:80"
    # mount the code folder to flaskr2 folder inside container so that
    # we don't have to rebuild when testing code
    volumes:
      - ./gatekeeper:/gatekeeper
  extractor:
    build: ./extractor
    command: python -u extractor.py
    ports:
      - "5000:5000"
    volumes:
      - ./extractor:/extractor
  mongo:
    image: mongo:3.4.6
